AWSTemplateFormatVersion: 2010-09-09
Description: Create the AppFlow resources required to buildt he Salesforce reporting pipeline
# Metadata: 

Parameters: 
  KmsArn:
    Description: KMS Key to use for encryption
    Type: String
  IntermediateBucket:
    Description: S3 Bucket to use for transfer
    Type: String
    AllowedPattern: "/^[a-z0-9][a-z0-9-]{1,60}[a-z0-9]$/"
    ConstraintDescription: "must be a valid S3 bucket name, see https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html"
  IntermediateBucketPrefix:
    Description: S3 bucket prefix for transfer
    Type: String
    AllowedPattern: "/^[^/\\s].*[^/\\s]$/"
    ConstraintDescription: "Prefix cannot start or end with whitespace or a '/'"
  ErrorBucket:
    Description: S3 Bucket to use for reporting errors
    Type: String
    AllowedPattern: "/^[a-z0-9][a-z0-9-]{1,60}[a-z0-9]$/"
    ConstraintDescription: "must be a valid S3 bucket name, see https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html"
  ErrorBucketPrefix:
    Description: S3 bucket prefix for errors
    Type: String
    AllowedPattern: "/^[^/\\s].*[^/\\s]$/"
    ConstraintDescription: "Prefix cannot start or end with whitespace or a '/'"
  SalesForceConnectionName:
    Description: name of the Saleforce Connection
    Type: String
  RedshiftConnectionName:
    Description: name of the Redshift Connection
    Type: String
  RedshiftTable:
    Description: name of the Redshift table to move the data into
    Type: String
Resources:
  SalesforceAccount:
    Properties:
      DestinationFlowConfigList:
      - ConnectorProfileName: !Ref RedshiftConnectionName
        ConnectorType: Redshift
        DestinationConnectorProperties:
          Redshift:
            bucketPrefix: !Ref IntermediateBucketPrefix
            errorHandlingConfig:
              bucketName: !Ref ErrorBucket
              bucketPrefix: !Ref ErrorBucketPrefix
              failOnFirstDestinationError: true
            intermediateBucketName: !Ref IntermediateBucket
            object: !Ref RedshiftTable
      FlowName: !Sub "${AWS::StanckName}-Salesforce-Account"
      KmsArn: !Ref KmsArn
      SourceFlowConfig:
        ConnectorProfileName: !Ref SalesForceConnectionName
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            enableDynamicFieldUpdate: false
            includeDeletedRecords: false
            object: Account
      Tags: {}
      Tasks:
      - ConnectorOperator:
          Salesforce: PROJECTION
        SourceFields:
        - Id
        - IsDeleted
        - MasterRecordId
        - JigsawCompanyId
        - Jigsaw
        - LastActivityDate
        - PhotoUrl
        - SystemModstamp
        - ShippingAddress
        - ShippingGeocodeAccuracy
        - ShippingCountry
        - ShippingPostalCode
        - ShippingState
        - ShippingCity
        - ShippingStreet
        - ShippingLongitude
        - ShippingLatitude
        - BillingAddress
        - BillingGeocodeAccuracy
        - BillingCountry
        - BillingPostalCode
        - BillingState
        - BillingCity
        - BillingStreet
        - BillingLongitude
        - BillingLatitude
        - Website
        - Type
        - LastReferencedDate
        - LastModifiedById
        - LastViewedDate
        - LastModifiedDate
        - Industry
        - Phone
        - Fax
        - ParentId
        - CreatedDate
        - NumberOfEmployees
        - AnnualRevenue
        - CreatedById
        - AccountSource
        - OwnerId
        - SicDesc
        - Name
        - Description
        TaskProperties: []
        TaskType: Filter
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: id
        SourceFields:
        - Id
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: id
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: deleted
        SourceFields:
        - IsDeleted
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: boolean
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: masterrecordid
        SourceFields:
        - MasterRecordId
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: reference
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: jigsawcompanyid
        SourceFields:
        - JigsawCompanyId
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: datacomkey
        SourceFields:
        - Jigsaw
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: lastactivity
        SourceFields:
        - LastActivityDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: date
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: photourl
        SourceFields:
        - PhotoUrl
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: url
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: systemmodstamp
        SourceFields:
        - SystemModstamp
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: datetime
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippingaddress
        SourceFields:
        - ShippingAddress
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: address
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippinggeocodeaccuracy
        SourceFields:
        - ShippingGeocodeAccuracy
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: picklist
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippingcountry
        SourceFields:
        - ShippingCountry
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippingzippostalcode
        SourceFields:
        - ShippingPostalCode
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippingstateprovince
        SourceFields:
        - ShippingState
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippingcity
        SourceFields:
        - ShippingCity
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippingstreet
        SourceFields:
        - ShippingStreet
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: textarea
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippinglongitude
        SourceFields:
        - ShippingLongitude
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        - Key: SOURCE_DATA_TYPE
          Value: double
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: shippinglatitude
        SourceFields:
        - ShippingLatitude
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        - Key: SOURCE_DATA_TYPE
          Value: double
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billingaddress
        SourceFields:
        - BillingAddress
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: address
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billinggeocodeaccuracy
        SourceFields:
        - BillingGeocodeAccuracy
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: picklist
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billingcountry
        SourceFields:
        - BillingCountry
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billingzippostalcode
        SourceFields:
        - BillingPostalCode
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billingstateprovince
        SourceFields:
        - BillingState
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billingcity
        SourceFields:
        - BillingCity
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billingstreet
        SourceFields:
        - BillingStreet
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: textarea
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billinglongitude
        SourceFields:
        - BillingLongitude
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        - Key: SOURCE_DATA_TYPE
          Value: double
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: billinglatitude
        SourceFields:
        - BillingLatitude
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        - Key: SOURCE_DATA_TYPE
          Value: double
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: website
        SourceFields:
        - Website
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: url
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: type
        SourceFields:
        - Type
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: picklist
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: lastreferenceddate
        SourceFields:
        - LastReferencedDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: timestamp without time zone
        - Key: SOURCE_DATA_TYPE
          Value: datetime
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: lastmodifiedbyid
        SourceFields:
        - LastModifiedById
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: reference
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: lastvieweddate
        SourceFields:
        - LastViewedDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: timestamp without time zone
        - Key: SOURCE_DATA_TYPE
          Value: datetime
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: lastmodifieddate
        SourceFields:
        - LastModifiedDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: timestamp without time zone
        - Key: SOURCE_DATA_TYPE
          Value: datetime
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: industry
        SourceFields:
        - Industry
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: picklist
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: phone
        SourceFields:
        - Phone
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: phone
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: fax
        SourceFields:
        - Fax
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: phone
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: parentid
        SourceFields:
        - ParentId
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: reference
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: createddate
        SourceFields:
        - CreatedDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: timestamp without time zone
        - Key: SOURCE_DATA_TYPE
          Value: datetime
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: numberofemployees
        SourceFields:
        - NumberOfEmployees
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        - Key: SOURCE_DATA_TYPE
          Value: int
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: annualrevenue
        SourceFields:
        - AnnualRevenue
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        - Key: SOURCE_DATA_TYPE
          Value: currency
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: createdbyid
        SourceFields:
        - CreatedById
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: reference
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: accountsource
        SourceFields:
        - AccountSource
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: picklist
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: ownerid
        SourceFields:
        - OwnerId
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: reference
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: sicdescription
        SourceFields:
        - SicDesc
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: name
        SourceFields:
        - Name
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: string
        TaskType: Map
      - ConnectorOperator:
          Salesforce: NO_OP
        DestinationField: description
        SourceFields:
        - Description
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        - Key: SOURCE_DATA_TYPE
          Value: textarea
        TaskType: Map
      TriggerConfig:
        TriggerProperties: {}
        TriggerType: OnDemand
    Type: AWS::AppFlow::Flow

