AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for AppFlow'
Parameters:
  AppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Lead-Salesforce

  ConnectorProfileName: 
    Type: String
    Description: "Salesforce Connector name "
    # Default: aws_demo
  ChildStackPath:
    Description: "Path to child stack cfts"
    Type: String
    Default: "https://my-bucket-s3-name-s3-appflow.s3.amazonaws.com"
  S3BucketName:
    Type: String
    Description: S3 data bucket name

Resources:
  SaleforceFlow:
    Type: AWS::AppFlow::Flow
    Properties:
      Description: AppFlow Flow integrating Saleforce with a Redshift 

      DestinationFlowConfigList:
        - ConnectorType: !ImportValue ConnectorType
          ConnectorProfileName: !ImportValue CPRN
          DestinationConnectorProperties:
            Redshift:
              BucketPrefix: !ImportValue S3BucketPrefix
              ErrorHandlingConfig:
                FailOnFirstError: true
                BucketPrefix: Lead-Error
                BucketName: !ImportValue S3BucketName
              IntermediateBucketName: !ImportValue S3BucketName
              Object: ods.lead

      FlowName: !Ref AppFlowName
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorProfileName
        ConnectorType: Salesforce
        SourceConnectorProperties: 
          Salesforce:
            EnableDynamicFieldUpdate: false
            IncludeDeletedRecords: false
            Object: Lead
      Tasks:
        - TaskType: Filter
          SourceFields:
          - Company
          - City
          - Country
          - Address
          - AnnualRevenue
          - IsConverted
          - ConvertedDate
          - ConvertedAccountId
          - ConvertedContactId
          - ConvertedOpportunityId
          - CreatedById
          - CreatedDate
          - Jigsaw
          - IsDeleted
          - Description
          - NumberOfEmployees
          - EmailBouncedReason
          - Email
          - EmailBouncedDate
          - Name
          - FirstName
          - GeocodeAccuracy
          - IndividualId
          - Industry
          - LastModifiedById
          - LeadSource
          - LastName
          - Id
          - LastActivityDate
          - Longitude
          - Latitude
          - LastViewedDate
          - LastReferencedDate
          - LastModifiedDate
          - MasterRecordId
          - OwnerId
          - PhotoUrl
          - Phone
          - Rating
          - Status
          - Salutation
          - State
          - Street
          - SystemModstamp
          - IsUnreadByOwner
          - JigsawContactId
          - Website
          - PostalCode
          - Title
          ConnectorOperator:
            Salesforce: PROJECTION

        - TaskType: Map
          SourceFields:
            - Company
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: company
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - City
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: city
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Country
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: country
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Address
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: address
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: address

        - TaskType: Map
          SourceFields:
            - AnnualRevenue
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: annualrevenue
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: numeric
            - Key: SOURCE_DATA_TYPE
              Value: currency

        - TaskType: Map
          SourceFields:
            - IsConverted
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: converted
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - ConvertedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: converteddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: date
            - Key: SOURCE_DATA_TYPE
              Value: date

        - TaskType: Map
          SourceFields:
            - ConvertedAccountId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: convertedaccountid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - ConvertedOpportunityId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: convertedopportunityid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - CreatedById
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: createdbyid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - CreatedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: createddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - Jigsaw
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: datacomkey
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - IsDeleted
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: deleted
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - Description
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: description
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: textarea

        - TaskType: Map
          SourceFields:
            - NumberOfEmployees
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: employees
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: integer
            - Key: SOURCE_DATA_TYPE
              Value: int

        - TaskType: Map
          SourceFields:
            - EmailBouncedReason
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: emailbouncedreason
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Email
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: email
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: email

        - TaskType: Map
          SourceFields:
            - EmailBouncedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: emailbounceddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - Name
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: fullname
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - FirstName
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: firstname
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - GeocodeAccuracy
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: geocodeaccuracy
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - IndividualId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: individualid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - Industry
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: industry
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - LastModifiedById
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastmodifiedbyid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - LeadSource
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: leadsource
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - LastName
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastname
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Id
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: leadid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: id 
              
        - TaskType: Map
          SourceFields:
            - LastActivityDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastactivity
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: date
            - Key: SOURCE_DATA_TYPE
              Value: date 

        - TaskType: Map
          SourceFields:
            - Longitude
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: longitude
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: numeric
            - Key: SOURCE_DATA_TYPE
              Value: double

        - TaskType: Map
          SourceFields:
            - Latitude
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: latitude
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: numeric
            - Key: SOURCE_DATA_TYPE
              Value: double

        - TaskType: Map
          SourceFields:
            - LastViewedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastvieweddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - LastReferencedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastreferenceddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - LastModifiedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastmodifieddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone 
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - MasterRecordId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: masterrecordidreference
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - OwnerId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: ownerid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - PhotoUrl
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: photourl
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: url

        - TaskType: Map
          SourceFields:
            - Phone
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: phone
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: phone

        - TaskType: Map
          SourceFields:
            - Rating
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: rating
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Status
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: status
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Salutation
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: salutation
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - State
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: stateprovince
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Street
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: street
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: textarea

        - TaskType: Map
          SourceFields:
            - SystemModstamp
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: systemmodstamp
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - IsUnreadByOwner
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: unreadbyowner
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - JigsawContactId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: jigsawcontactid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Website 
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: website
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: url

        - TaskType: Map
          SourceFields:
            - PostalCode
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: zippostalcode
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Title
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: title
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: String


      TriggerConfig:
        TriggerType: Scheduled
        TriggerProperties:
          DataPullMode: Incremental
          ScheduleExpression: rate(59minutes)

  ActivateAppflowLambda:
    DependsOn: SaleforceFlow
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${ChildStackPath}/activate-appflow-lambda.cft.yaml
      Parameters:
        AppFlowName: !Ref AppFlowName