AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for AppFlow'
Parameters:
  AppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Case-Saleforce
  ConnectorProfileName:
    Type: String
    Description: "Salesforce Connector name "
    # Default: aws_demo
  ChildStackPath:
    Description: "Path to child stack cft"
    Type: String
    Default: "https://my-bucket-s3-name-s3-appflow.s3.amazonaws.com"
  S3BucketName:
    Type: String
    Description: S3 data bucket name
Resources:
  SaleforceFlow:
    Type: AWS::AppFlow::Flow
    Properties:
      Description: AppFlow Flow integrating Salesforce with a Redshift

      DestinationFlowConfigList:
        - ConnectorType: !ImportValue ConnectorType
          ConnectorProfileName: !ImportValue CPRN
          DestinationConnectorProperties:
            Redshift:
              BucketPrefix: !ImportValue S3BucketPrefix
              ErrorHandlingConfig:
                FailOnFirstError: true
                BucketPrefix: Case-Error
                BucketName: !ImportValue S3BucketName
              IntermediateBucketName: !ImportValue S3BucketName
              Object: ods.case

      FlowName: !Ref AppFlowName

      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorProfileName
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            EnableDynamicFieldUpdate: false
            IncludeDeletedRecords: false
            Object: Case


      Tasks:
        - TaskType: Filter
          SourceFields:
          - Id
          - IsDeleted
          - MasterRecordId
          - CaseNumber
          - ContactId
          - AccountId
          - ParentId
          - SuppliedName
          - SuppliedEmail
          - SuppliedPhone
          - SuppliedCompany
          - Type
          - Status
          - Reason
          - Subject
          - Priority
          - Description
          - IsClosed
          - ClosedDate
          - IsEscalated
          - OwnerId
          - CreatedDate
          - CreatedById
          - LastModifiedDate
          - LastModifiedById
          - SystemModstamp
          - ContactPhone
          - ContactMobile
          - ContactEmail
          - ContactFax
          - Comments
          - LastViewedDate
          - LastReferencedDate
          - Origin
          ConnectorOperator:
            Salesforce: PROJECTION

        - TaskType: Map
          SourceFields:
            - Id
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: caseid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: id

        - TaskType: Map
          SourceFields:
            - IsDeleted
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: deleted
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - MasterRecordId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: masterrecordid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - CaseNumber
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: casenumber
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: casenumber
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - ContactId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contactid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - AccountId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: accountid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - ParentId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: parentcaseid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - SuppliedName
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: name
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - SuppliedEmail
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: emailaddress
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: email

        - TaskType: Map
          SourceFields:
            - SuppliedPhone
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: phone
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - SuppliedCompany
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: company
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Type
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: casetype
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Status
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: status
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Reason
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: casereason
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Subject
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: subject
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Priority
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: priority
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Description
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: description
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: textarea

        - TaskType: Map
          SourceFields:
            - IsClosed
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: closed
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - ClosedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: closeddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - IsEscalated
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: escalated
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - OwnerId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: ownerid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - CreatedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: createddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: time without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - CreatedById
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: createdbyid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - LastModifiedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastmodifieddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - LastModifiedById
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastmodifiedbyid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - SystemModstamp
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: systemmodstamp
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - ContactPhone
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contactphone
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: phone

        - TaskType: Map
          SourceFields:
            - ContactMobile
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contactmobile
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: phone

        - TaskType: Map
          SourceFields:
            - ContactEmail
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contactemail
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: email

        - TaskType: Map
          SourceFields:
            - ContactFax
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contactfax
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: phone

        - TaskType: Map
          SourceFields:
            - Comments
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: internalcomments
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: textarea

        - TaskType: Map
          SourceFields:
            - LastViewedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastvieweddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - LastReferencedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastreferenceddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - Origin
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: caseorigin
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

      TriggerConfig:
        TriggerType: Scheduled
        TriggerProperties:
          DataPullMode: Incremental
          ScheduleExpression: rate(59minutes)

  ActivateAppflowLambda:
    DependsOn: SaleforceFlow
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${ChildStackPath}/activate-appflow-lambda.template.yaml
      Parameters:
        AppFlowName: !Ref AppFlowName