AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for AppFlow'
Parameters:
  AppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Opportunity-Salesforce
  ConnectorProfileName: 
    Type: String
    Description: "Salesforce Connector name "
    Default: aws_demo
  ChildStackPath:
    Description: "Path to child stack cfts"
    Type: String
    Default: "https://my-bucket-s3-name-s3-appflow.s3.amazonaws.com"
  S3BucketName:
    Type: String
    Description: S3 data bucket name
  # appflow-salesforce-keyrus
Resources:
  SaleforceFlow:
    Type: AWS::AppFlow::Flow
    Properties:
      Description: AppFlow Flow integrating Saleforce with a Redshift 

      DestinationFlowConfigList:
        - ConnectorType: !ImportValue ConnectorType
          ConnectorProfileName: !ImportValue CPRN
          DestinationConnectorProperties:
            Redshift:
              BucketPrefix: !ImportValue S3BucketPrefix
              ErrorHandlingConfig:
                FailOnFirstError: true
                BucketPrefix: Opportunity-Error
                BucketName: !ImportValue S3BucketName
              IntermediateBucketName: !ImportValue S3BucketName
              Object: ods.opportunity

      FlowName: !Ref AppFlowName
      # kmsARN:
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorProfileName
        ConnectorType: Salesforce
        SourceConnectorProperties: 
          Salesforce:
            EnableDynamicFieldUpdate: false
            IncludeDeletedRecords: false
            Object: Opportunity
      Tasks:
        - TaskType: Filter
          SourceFields:
          - HasOverdueTask
          - HasOpenActivity
          - HasOpportunityLineItem
          - IsWon
          - IsClosed
          - IsDeleted
          - FiscalYear
          - FiscalQuarter
          - Amount
          - ContactId
          - CreatedById
          - LastAmountChangedHistoryId
          - Fiscal
          - LastModifiedById
          - OwnerId
          - Pricebook2Id
          - CampaignId
          - ForecastCategory
          - Type
          - LeadSource
          - NextStep
          - StageName
          - Name
          - CloseDate
          - AccountId
          - Id
          - LastActivityDate
          - LastModifiedDate
          - CreatedDate
          - LastReferencedDate
          - LastViewedDate
          - SystemModstamp
          - Probability
          - Description
          ConnectorOperator:
            Salesforce: PROJECTION

        - TaskType: Map
          SourceFields:
            - HasOverdueTask
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: hasoverduetask
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - HasOpenActivity
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: hasopenactivity
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - HasOpportunityLineItem
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: haslineitem
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - IsWon
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: won
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - IsClosed
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: closed
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: boolean
            - Key: SOURCE_DATA_TYPE
              Value: boolean

        - TaskType: Map
          SourceFields:
            - FiscalYear
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: fiscalyear
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: integer
            - Key: SOURCE_DATA_TYPE
              Value: int

        - TaskType: Map
          SourceFields:
            - FiscalQuarter
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: fiscalquarter
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: integer
            - Key: SOURCE_DATA_TYPE
              Value: int

        - TaskType: Map
          SourceFields:
            - Amount
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: amount
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: integer
            - Key: SOURCE_DATA_TYPE
              Value: currency

        - TaskType: Map
          SourceFields:
            - ContactId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contactid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference

        - TaskType: Map
          SourceFields:
            - CreatedById
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: createdbyid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference          

        - TaskType: Map
          SourceFields:
            - LastAmountChangedHistoryId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: opportunityhistoryid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - Fiscal
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: fiscalperiod
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - LastModifiedById
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastmodifiedbyid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - OwnerId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: ownerid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - Pricebook2Id
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: pricebookid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - CampaignId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: campaignid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - ForecastCategory
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: forecastcategory
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Type
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: opportunitytype
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - LeadSource
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: leadsource
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - NextStep
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: nextstep
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - StageName
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: stage
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Name
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: name
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - CloseDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: closedate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: date
            - Key: SOURCE_DATA_TYPE
              Value: date

        - TaskType: Map
          SourceFields:
            - AccountId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: accountid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: reference 

        - TaskType: Map
          SourceFields:
            - Id
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: opportunityid
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: id

        - TaskType: Map
          SourceFields:
            - LastActivityDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastactivity
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: date
            - Key: SOURCE_DATA_TYPE
              Value: date

        - TaskType: Map
          SourceFields:
            - LastModifiedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastmodifieddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: date
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - CreatedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: createddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: date
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - LastReferencedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastreferenceddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - LastViewedDate
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: lastvieweddate
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - SystemModstamp
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: systemmodstamp
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: timestamp without time zone
            - Key: SOURCE_DATA_TYPE
              Value: datetime

        - TaskType: Map
          SourceFields:
            - Probability
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: probabilitypercentage
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: numeric
            - Key: SOURCE_DATA_TYPE
              Value: percent

        - TaskType: Map
          SourceFields:
            - Description
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: description
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: textarea

      # TriggerConfig:
      #   TriggerType: OnDemand

      TriggerConfig:
        TriggerType: Scheduled
        TriggerProperties:
          DataPullMode: Incremental
          ScheduleExpression: rate(59minutes)

  ActivateAppflowLambda:
    DependsOn: SaleforceFlow
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${ChildStackPath}/activate-appflow-lambda.cft.yaml
      Parameters:
        AppFlowName: !Ref AppFlowName
        
  