AWSTemplateFormatVersion: '2010-09-09'
Description: Root CloudFormation Template (qs-1t7ksiu2s)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into a new VPC"
    Order: 1
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - ConnectorProfileName
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
      - Label:
          default: Keyrus configuration
        Parameters:
          - ConnectorProfileName
          - S3BucketName
          - LeadAppFlowName
          - ContactAppFlowName
          - CaseAppFlowName
          - AccountAppFlowName
          - OpportunityAppFlowName
      - Label:
          default: Redshift configuration
        Parameters:
          - RedShiftUsername
          - RedShiftUserPassword
          - S3BucketPrefix
          - EnableLoggingToS3
          - RedShiftConnectorProfileName
          - ConnectionModeVal
          - ConnectorType
          - NumberOfNodes
          - NodeType
          - EncryptionAtRest
          - KMSKey
    ParameterLabels:
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      ConnectorProfileName:
        default: Production radio box from the Salesforce environment section
      NodeType:
        default: Node type
      S3BucketName:
        default: Bucket for AppFlow
      RedShiftUsername:
        default: Redshift User Name
      RedShiftUserPassword:
        default: Redshift User Password
      S3BucketPrefix:
        default: S3 Bucket Prefix for logging bucket
      EnableLoggingToS3:
        default: Enables or disables logging to an S3 bucket.
      RedShiftConnectorProfileName:
        default: Connection Profile name for RedShift.
      ConnectionModeVal:
        default: Connection Mode for Connection Profile
      ConnectorType:
        default: Connection Profile Type
      EncryptionAtRest:
        default: Enables or disables encryption at rest of the Redshift database.
      KMSKey:
        default: KMS key used for RedShift encryption at rest
      LeadAppFlowName:
        default: "Name of the flow"
      ContactAppFlowName:
        default: "Name of the flow"
      CaseAppFlowName:
        default: "Name of the flow"
      AccountAppFlowName:
        default: "Name of the flow"
      OpportunityAppFlowName:
        default: "Name of the flow"
Parameters:
  ConnectorProfileName:
    Description: "Select the Production radio box from the Salesforce environment section. Enter the connection name and click Continue. The Connection name must match in every single Cloudformation template for AppFlow logs or any other desired name."
    Type: String
    Default: aws_demo
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), periods (.) and forward slash (/).
    Default: quickstart-keyrus-salesforce-reporting/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), periods (.) and
      forward slash (/).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: Region where the Quick Start S3 bucket (QSS3BucketName) is
      hosted. When using your own bucket, you must specify this value.
    Type: String
  S3BucketName:
    Type: String
    Description:  "S3 bucket where Amazon AppFlow will write data"
  RedShiftUsername:
    Type: String
    Description: Redshift user name for Redshift
  RedShiftUserPassword:
    Description: Redshift password for Redshift (used mixed case and numbers) Make Sure this is solid something with special characters.
    Type: String
    NoEcho: 'true'
    MinLength: '8'
    MaxLength: '64'
    AllowedPattern: ^(?=^.{8,255}$)(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9])(?!.*[@/"']).*$
    ConstraintDescription: "Min 8 chars. Must include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ \" ') symbol"
  NumberOfNodes:
    Description: >-
      The number of compute nodes in the cluster. For multi-node clusters, the NumberOfNodes parameter must be greater than 1.
    Type: Number
    Default: '1'
  NodeType:
    Description: The type of node to be provisioned
    Type: String
    Default: dc2.large
    AllowedValues:
      - dc2.large
      - dc2.8xlarge
      - ds2.xlarge
      - ds2.8xlarge
  S3BucketPrefix:
    Description: The Prefix name for the S3 Bucket
    Type: String
    Default: 'Logs/'
  EnableLoggingToS3:
    Default: true
    Type: String
    AllowedValues:
      - true
      - false
    Description: Enables or disables logging to an S3 bucket.  To enable logging, select True.
  RedShiftConnectorProfileName:
    Description: "Connection Profile name for RedShift."
    Type: String
    Default: 'Hello'
  ConnectionModeVal:
    Default: 'Public'
    Type: String
    AllowedValues:
      - 'Public'
      - 'Private'
    Description: Connection Mode for Connection Profile
  ConnectorType:
    Default: 'Redshift'
    Type: String
    AllowedValues:
      - 'Redshift'
      - 'Salesforce'
    Description: Connection Profile Type
  EncryptionAtRest:
    Description: Enables or disables encryption at rest of the Redshift database.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be true or false.
  KMSKey:
    Description: The existing KMS key ID for encrypting Redshift database at-rest ( Add if EncryptionAtRest enabled ).
    Type: String
    Default: ''
  AccountAppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Account-Saleforce
  CaseAppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Case-Saleforce
  ContactAppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Contact-Salesforce
  LeadAppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Lead-Salesforce
  OpportunityAppFlowName:
    Description: "Name of the flow"
    Type: String
    Default: Opportunity-Salesforce
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  SaleForceRedshift:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/quickstart-salesforce-redshift.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        S3BucketName: !Ref S3BucketName
        RedShiftUsername: !Ref RedShiftUsername
        RedShiftUserPassword: !Ref RedShiftUserPassword
        NumberOfNodes: !Ref NumberOfNodes
        NodeType: !Ref NodeType
        ConnectorProfileName: !Ref RedShiftConnectorProfileName
        ConnectionModeVal: !Ref ConnectionModeVal
        ConnectorType: !Ref ConnectorType
        EncryptionAtRest: !Ref EncryptionAtRest
        KMSKey: !Ref KMSKey
        S3BucketPrefix: !Ref S3BucketPrefix
        EnableLoggingToS3: !Ref EnableLoggingToS3
  AppflowAccount:
    DependsOn: SaleForceRedshift
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/appflow-salesforce-account.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        ConnectorProfileName: !Ref ConnectorProfileName
        AppFlowName: !Ref AccountAppFlowName
        S3BucketName: !Ref S3BucketName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}'
  AppflowCase:
    DependsOn: SaleForceRedshift
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/appflow-salesforce-case.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        ConnectorProfileName: !Ref ConnectorProfileName
        S3BucketName: !Ref S3BucketName
        AppFlowName: !Ref CaseAppFlowName
  AppflowContact:
    DependsOn: SaleForceRedshift
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/appflow-salesforce-contact.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        ConnectorProfileName: !Ref ConnectorProfileName
        AppFlowName: !Ref ContactAppFlowName
        S3BucketName: !Ref S3BucketName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}'
  AppflowLead:
    DependsOn: SaleForceRedshift
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/appflow-salesforce-lead.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        ConnectorProfileName: !Ref ConnectorProfileName
        S3BucketName: !Ref S3BucketName
        AppFlowName: !Ref LeadAppFlowName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}'
  AppflowOpportunity:
    DependsOn: SaleForceRedshift
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/appflow-salesforce-opportunity.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        ConnectorProfileName: !Ref ConnectorProfileName
        S3BucketName: !Ref S3BucketName
        AppFlowName: !Ref OpportunityAppFlowName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}'

