AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample CloudFormation Template for AppFlow: Sample template shows how
  to create a flow with parameters'
Parameters:
  flowname:
    Description: "Name of the flow"
    Type: String
    Default: Account_Saleforce



Resources:



  SaleforceFlow:
    Type: AWS::AppFlow::Flow
    Properties:
      Description: AppFlow Flow integrating Saleforce with a Redshift 

      DestinationFlowConfigList:
        - ConnectorType: !ImportValue ConnectorType
          ConnectorProfileName: !ImportValue CPRN
          DestinationConnectorProperties:
            Redshift:
              BucketPrefix: !ImportValue S3BucketPrefix
              ErrorHandlingConfig:
                FailOnFirstError: true
                BucketPrefix: Account-Error
                BucketName: !ImportValue S3BucketName
              IntermediateBucketName: !ImportValue S3BucketName
              Object: ods.account

      FlowName: !Ref flowname
      SourceFlowConfig:
        ConnectorProfileName: Keyrus
        ConnectorType: Salesforce
        SourceConnectorProperties: 
          Salesforce:
            EnableDynamicFieldUpdate: false
            IncludeDeletedRecords: false
            Object: Account
      Tasks:
        - TaskType: Filter
          SourceFields:
          - Name
          - Type
          - ParentId
          - Phone
          - Fax
          - Website
          - Industry
          - AnnualRevenue 
          ConnectorOperator:
            Salesforce: PROJECTION

        - TaskType: Map
          SourceFields:
            - Name
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: name
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: string

        - TaskType: Map
          SourceFields:
            - Type
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: type
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - ParentId
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: type
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map
          SourceFields:
            - Phone
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: phone
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: phone

        - TaskType: Map 
          SourceFields:
            - Fax
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: fax
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: phone

        - TaskType: Map 
          SourceFields:
            - Website
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: website
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: url

        - TaskType: Map 
          SourceFields:
            - Industry
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: industry
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: character varying
            - Key: SOURCE_DATA_TYPE
              Value: picklist

        - TaskType: Map 
          SourceFields:
            - AnnualRevenue
          ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: annualrevenue
          TaskProperties:
            - Key: DESTINATION_DATA_TYPE
              Value: numeric
            - Key: SOURCE_DATA_TYPE
              Value: currency

      TriggerConfig:
        TriggerType: OnDemand





